package main

import (
	"fmt"
	"os"
	"os/exec"
	"text/template"
)

const configDir = "/etc/openvpn/server"

// Template for the open vpn config files we generate.
var openVpnCfgTpl = template.Must(template.New("openvpn-config").Parse(`
# This file is automatically generated by hil-vpn-privop; do not modify manually.

dev tap-hil-vpn-{{ .Name }}
secret hil-vpn-{{ .Name }}.key

# The default cipher is insecure, so we explicitly set the cipher to the openvpn
# project's recommendation. See https://community.openvpn.net/openvpn/wiki/SWEET32
cipher AES-256-CBC

lport {{ .Port }}

user nobody
group nobody
`))

type OpenVpnCfg struct {
	Name string
	Key  string
	Port uint16
}

// Get the path to the file in which to store the openvpn config for the
// named vpn.
func getCfgPath(name string) string {
	return configDir + "/" + name + ".conf"
}

// Get the path to the file in which to store the key for the named vpn.
func getKeyPath(name string) string {
	return configDir + "/hil-vpn-" + name + ".key"
}

// Get the name of the systemd service for the named vpn.
func getServiceName(vpnName string) string {
	return "openvpn-server@" + vpnName
}

// Save the openvpn config and its static keys to disk.
func (cfg OpenVpnCfg) Save() error {
	cfgPath := getCfgPath(cfg.Name)
	keyPath := getKeyPath(cfg.Name)

	cfgFile, err := os.OpenFile(cfgPath, os.O_CREATE|os.O_EXCL|os.O_RDWR, 0600)
	if err != nil {
		return err
	}
	defer func() {
		cfgFile.Close()
		if err != nil {
			os.Remove(cfgPath)
		}
	}()
	keyFile, err := os.OpenFile(keyPath, os.O_CREATE|os.O_EXCL|os.O_RDWR, 0600)
	if err != nil {
		return err
	}
	defer func() {
		keyFile.Close()
		if err != nil {
			os.Remove(keyPath)
		}
	}()
	if err = openVpnCfgTpl.Execute(cfgFile, cfg); err != nil {
		return err
	}
	_, err = keyFile.Write([]byte(cfg.Key))
	return err
}

// Generate a new openvpn config (including a static key).
func NewOpenVpnConfig(name string, port uint16) (*OpenVpnCfg, error) {
	cmd := exec.Command("openvpn", "--genkey", "--secret", "/dev/fd/1")
	output, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("Error invoking openvpn: %v", err)
	}
	return &OpenVpnCfg{
		Name: name,
		Port: port,
		Key:  string(output),
	}, nil
}
