// Package staticconfig contains constants for compile-time configuration
// variables. Right now this is just various directory paths that would
// otherwise be hard-coded; These are generated by the `Makefile` in the
// top level directory.
package staticconfig

var (
	// Directories for various system paths. See:
	//
	// https://www.gnu.org/prep/standards/standards.html#Directory-Variables
	//
	// ...and the comments in the Makefile. These get overriden at link-time.
	Prefix         string
	Execprefix     string
	Bindir         string
	Sbindir        string
	Libexecdir     string
	Datarootdir    string
	Datadir        string
	Sysconfdir     string
	Sharedstatedir string
	Localstatedir  string
	Runstatedir    string
	Includedir     string
	Oldincludedir  string
	Docdir         string
	Infodir        string
	Htmldir        string
	Dvidir         string
	Pdfdir         string
	Psdir          string
	Libdir         string
	Localedir      string
	Mandir         string
)
